const dico = [
["exprès","se","exprès expresse$4","expresse$4","exprès"],
["sauf","(au)?ve","sauf$5 sauve$5","sauve$5","sauf$5","auve","ve"],
["([vn])euf","(eu)?ve","$2$6 $3euve$6","$3euve$6","$2$6","euve","ve"],
["serf","(er)?ve","serf$5 serve$5","serve$5","serf$5","erve","ve"],
["roux","(ou)?sse","roux rousse$5","rousse$5","roux","ousse","sse"],
["faux","(au)?sse","faux fausse$5","fausse$5","faux","ausse","sse"],
["vieux","i?eille","vieux vieille$4","vieille$4","vieux","ieille"],
["copain","ine","copain$4 copine$4","copine$4","copain$4","ine"],
["br[èe]f","è?ve","bref$4 brève$4","brève$4","bref$4","ève"],
["compagnon","agne","compagnon$4 compagne$4","compagne$4","compagnon$4","agne","ne"],
["tiers?","ce","tiers tierce$4","tierce$4","tiers","ce"],
["doux","(?:ou)?ce","doux douce$4","douce$4","doux","ouce","ce"],
["hébreux?","aïque","hébreux hébraïque$4","hébraïque$4","hébreux","aïque"],
["fra[iî]s?","(aî)?che","frais fraîche$5","fraîche$5","frais","che","aîche"],
["s[èe]c","è?c?he","sec$4 sèche$4","sèche$4","sec$4","èche","he"],
["docteur","oresse","docteur$4 doctoresse$4","doctoresse$4","docteur$4","e","oresse"],
["héros?","o?ïne","héros héroïne$4","héroïne$4","héros","oïne"],
["aïeux","(?:ieu)?le","aïeux aïeule$4","aïeule$4","aïeux","ïeule"],
["canut","u?se","canut$4 canuse$4","canuse$4","canut$4","use"],
["bêta","a?sse","bêta$4 bêtasse$4","bêtasse$4","bêta$4","sse","asse"],
["clown","e(?:sse)","clown$4 clown$3$4","clown$3$4","clown$4","e","esse"],
["(bén|mal)in","igne","$3in$5 $3igne$5","$3igne$5","$3in$5","igne"],
["(diss|abs)ous?","(ou)?te","$3ous $3oute$6","$3oute$6","$3ous","oute","te"],
["(ép|jal)oux","(ou)?se","$3oux $3ouse$6","$3ouse$6","$3oux","ouse","se"],
["blanc|franc","he","$2$4 $2he$4","$2he$4","$2$4","he"],
["prophète","e?sse","prophète$4 prophétesse$4","prophétesse$4","prophète$4","sse","esse"],
["long","ue","$1long$4 $1longue$4","$1longue$4","$1long$4","ue"],
["butor|esquimau","de","$2$4 $2de$4","$2de$4","$2$4","de"],
["esquimaux","des?","esquimaux esquimaudes","esquimaudes","esquimaux","des"],
["andalou","se","$2$4 $2se$4","$2se$4","$2$4","se"],
["foufou","olle","foufou$4 fofolle$4","fofolle$4","foufou$4","olle"],
["([mf])ou","olle","$3ou$5 $3olle$5","$3olle$5","$3ou$5","olle"],
["acquéreur","esse|euse","acquéreur$4 acquér$3$4","acquér$3$4","acquéreur$4","esse"],
["devin","eresse","devin$4 devineresse$4","devineresse$4","devin$4","eresse"],
["eaux","elles?","$1$2 $1$3$4","$1$3$4","$1$2"],
["eau","elle","$1$2 $1$3","$1$3","$1$2"],
["aux","ales?","$1$2 $1$3$4","$1$3$4","$1$2"],
["eux","euse","$1$2$4 $1$3$4","$1$3$4","$1$2$4","euse","se"],
["(pêch|chass|b[âa]ill|charm|emmerd|impost|pip|pren|sing|taill|vend|demand|veng)eur","(eu)?se","$3eur$6 $3euse$6","$3euse$6","$3eur$6","eresse","euse","se",""],
["(vainq|assess|gouvern|prédécess)eur","(eu)?se","$3eur$6 $3euse$6","$3euse$6","$3eur$6","e","euse","eresse","se"],
["(défend|paqu|codemand|enchant|p[éè]ch)eur","eresse","$3eur$6 $3eresse$6","$3eresse$6","$3eur$6","eresse"],
["eur","eresse","$1$2$4 $1$3$4","$1$3$4","$1$2$4"],
["ambassadeur","d?r?ice","ambassadeur$4 ambassadrice$4","ambassadrice$4","ambassadeur$4","drice","rice","ice"],
["(t)eu?r","t?r?ice","$1$2$5 $1$3rice$5","$1$3rice$5","$1$2$5","trice","euse","rice","se"],
["e(u)?r","(?:eu)?se","$1euse$5","$1euse$5","$1e$3r$5"],
["(lasc|noc|malad|tard|na|ju|v|réflex|[st])([ïi])f","[iï]?ve","$1$2$6 $1$3$4ve$6","$1$3$4ve$6","$1$2$6","ive","ve"],
["le|au|du", "(à |de )?l?aquel[-/·∙.•]le","$2quel $4 laquelle","$4 laquelle","$2quel"],
["du|au","(?:de|à) la","$2 $3","$3","$2"],
["tous?","te","tous toutes","toutes","tous"],
["le","l?a","le la","la","le"],
["ils?","elle","il$4 elle$4","elle$4","il$4"],
["([mts])on","[mts]a","$3on $3a","$3a","$3a","$3on"],
["celui","c?elle","celui celle","celle","celui"],
["ceux","c?elle","ceux celles","celles","ceux"],
["lui","elle","lui elle","elle","lui"],
["eux","elles","eux elles","elles","eux"],
["[^e]","esse","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["e","esse","$1$2$4 $1$3$4","$1$3$4","$1$2$4"],
["e","sse","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["favori|rigolo|filou|loulou|coi","te","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4","te"],
["((in)?compl|concr|désu|(in)?discr|inqui|préf|repl|secr|qui|rondel)et","ète","$3et$7 $3ète$7","$3ète$7","$3et$7","ète"],
["[èe]([rt])","(?:è[rt])?e","$1e$3$5 $1è$3e$5","$1è$3e$5","$1e$3$5"], // shortcut
//["er","ère","$1$2$4 $1ère$4","$1ère$4","$1$2$4"],
//["èr","e","$1er$4 $1ère$4","$1ère$4","$1er$4"],
//["[ntl]","[ntl]e","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"], // shortcut for 3 next
["t","te","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["n","ne","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["l","le","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["las|bas|gros|gras|épais","se","$2 $2se$4","$2se$4","$2","se"],
["s","ses?","$1s $1$2$3$4","$1$2$3$4","$1s"],
["","se","$1s $1$2$3$4","$1$2$3$4","$1s"],
["","ss","$1sse $1sse$4","$1sse$4","$1sse"],
["s","e","$1s $1se$4","$1se$4","$1s"],
["[ndt]","e","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["chef","fe","chef$4","cheffe$4","chef$4","fe","fesse"],
["grec","que","grec$4","grecque$4","grec$4","que"],
["(cadu|laï|publi|micma|syndi|tur|fran)c","que","$3c$5","$3que$5","$3c$5","que"],
["[éilr]","e","$1$2$4","$1$2$3$4","$1$2$4"],
["(ai|ambi|bé|conti|exi|surai|subai)g[uü]","[eë]","$3gu$5","$3guë$5","$3gu$5","ë","e"],
["u","e","$1$2$4","$1$2$3$4","$1$2$4"],
["û","e","$1$2$4","$1u$3$4","$1$2$4"]
];