const dico = [
["br[èe]f","è?ve","bref$4 brève$4","brève$4","bref$4","ève"],
["s[èe]c","è?c?he","sec$4 sèche$4","sèche$4","sec$4","èche","he"],
["fra[iî]s?","a?[iî]?che","frais fraîche$4","fraîche$4","frais","che","aîche"],
["prophète","e?sse","prophète$4 prophétesse$4","prophétesse$4","prophète$4","sse","esse"],
["foufou","olle","foufou$4 fofolle$4","fofolle$4","foufou$4","olle"],
["héros?","o?ïne","héros héroïne$4","héroïne$4","héros","oïne"],
["franc","que","franc$4 franque$4","franque$4","franc$4"],
["aïeux","(?:ïeu)?le","aïeux aïeule$4","aïeule$4","aïeux"],
["vieux","i?eille","vieux vieille$4","vieille$4","vieux"], 
["grec|clown|blanc|franc(?!·que)|long|butor|esquimau|andalou|devin|favori|rigolo|filou|loulou|coi|ce","(?:er)?esse|[hudst]e|tte|que","$2$4 $2$3$4","$2$3$4","$2$4"],
["eur","(?:[oe]r)?esse","$1$2$4 $1$3$4","$1$3$4","$1$2$4"],
["([td])eu?r","[td]?r?ice","$1$2$5 $1$3rice$5","$1$3rice$5","$1$2$5"],
["e(u)?r","(?:eu)?se","$1e$3r$5 $1euse$5","$1euse$5","$1e$3r$5"],
["([ïuri])f","(?:au|eu|er|[iï])?ve","$1$2$5 $1$3ve$5","$1$3ve$5","$1$2$5"],
["([eoa]u)x","(?:[oea]u)?([sdc]{1,2}e)","$1$3x $1$3$5$6","$1$3$5$6","$1$3x"],
["e?aux?","elle|ale","$1$2 $1$3$4","$1$3$4","$1$2"],
["a?in|agnon|ou|ut|a","[ia]g?ne|olle|asse|use","$1$2$4 $1$3$4","$1$3$4","$1$2$4"], 
["(absou|dissou|tou|tier)s?","(ou)?(te)|(ce)","$3s $3$6$7$8","$3$6$7$8","$3s"],
["[èe]([rnt])","(?:è[rnt])?e","$1e$3$5 $1è$3e$5","$1è$3e$5","$1e$3$5"], 
["le|au|du", "(à |de )?l?aquel[-/·∙.•]le","$2quel $4 laquelle","$4 laquelle","$2quel"],
["du|au","(?:de|à) la","$2 $3","$3","$2"],
["le","l?a","le la","la","le"],
["([mts])on","[mts]a","$3on $3a","$3a","$3a","$3on"],
["ils?","elle","il$4 elle$4","elle$4","il$4"],
["eux|e?lui|ils?","c?elle","$1$2 $1elle$4","$1elle$4","$1$2"],
["t","te","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["n","ne","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["pareil|vermeil|bel|nouvel|vieil|fol|mol","le","$2","$2le","$2"],
["il","le","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"], 
["[aeou]l","le","$1$2$4","$1$2$3$4","$1$2$4"], 
["(e)|([^e])","e?sse","$1$3$4$6 $1$4esse","$1$4esse","$1$3$4$6"], 
["s","se","$1s $1$2$3$4","$1$2$3$4","$1s"],
["[ndt]h?","e","$1$2$4 $1$2$3$4","$1$2$3$4","$1$2$4"],
["([féilruüzhk])|(c)","(f|qu)?[ëe]","$1$3$4$7","$1$3$5$7","$1$3$4"], 
["û","e","$1u$4","$1ue$4","$1u$4"],
["s","e","$1s $1se$4","$1se$4","$1s"],
["","se","$1s $1se$4","$1se$4","$1s"]
],
t9 = [
["(ai|ambi|bé|conti|exi|surai|subai)g[uü]","ë","e"],
["(gre|cadu|laï|publi|micma|syndi|tur|fran)c","que"],
["vi eux","ieille"],
["hébreux?","aïque"],
["aïeux","ïeule"],
["[a-zÀ-ÖÙ-öù-üœŒ]+eux","euse","se"],
["lesquel|auxquel|desquel","les"],
["((in)?compl|concr|désu|(in)?discr|inqui|préf|repl|secr|qui|rondel)et","ète"],
["(diss|abs)ous","oute","te"],
["([bc]|aigl|sax|bar|berrich|bis|b|bouff|bourguign|bûcher|bret|brouill|b[uû]cher|buffl|champi|coch|couill|cret|dar|drag|espi|fanfar|fél|folich|forger|frip|maç|lett|garç|gasc|glout|grogn|hériss|hur|laider|lap|lett|li|tatill|teut|champi|vigner|wall|lur|maç|maigrich|nipp|ours|pâlich|phara|piét|pige|pi|pochetr|pochtr|poliss|poltr|rejet|ronch|sauvage|sax|beaucer|bess|bich|boug|brabanç|charr|enfanç|fransquill|godich|hesbign|marmit|nazill|négrill|noblaill|patr|percher|pa|levr|louch|maquign|marr|mat|slav|so[uû]l|mign|mist|mollass|tâcher|tardill)on","ne"],
["âne|comte|bonze|bougre|buffle|chanoine|sauvage|tigre|traître|type|prêtre|prince|prophète|faune|flique|gonze|hôte|ivrogne|ladre|larronne|maire|maître|monstre|nègre|notaire|ogre|paire|pape|patronne|pauvre|drôle|druide|comte|diable|suisse|mulâtre|centaure|chanoine","sse","esse"],
["(damois|cham|jum|puc|tourang|tourter|jouvenc|maquer|ois|nouv|gém|pastour|agn|b)eaux?","elle"],
["sculpteur","e","euse","rice"],
["(pêch|chass|b[âa]ill|charm|emmerd|impost|pip|pren|sing|taill|vend|demand|veng)eur","eresse","euse","se"],
["chat|rat|filou|loulou|favori|rigolo|coi|((maigri|pâl|bosc|jeun|vieill|s)ot)","te"],
["(vainq|assess|gouvern|prédécess)eur","e","euse","eresse","se"],
["(défend|paqu|codemand|enchant|p[éè]ch)eur","eresse"],
["ambassadeur","drice","rice","ice"],
["docteur","e","oresse"],
["acquéreur","euse","esse"],
["([a-zÀ-ÖÙ-öù-üœŒ]+ier)|(am|arch|berg|bocag|bouch|boulang|cach|caloy|ch|coch|conseill|écaill|écuy|étrang|fromag|gauch|horlog|khm|lég|lignag|ling|magist|maraîch|mast|ménag|mensong|métay|passag|paysag|péag|porch|potag|sup|usag|vach)er","ère"],
["(lasc|noc|malad|tard|na|ju|v|réflex|[st])([ïi])f","ive","ve"],
["[a-zÀ-ÖÙ-öù-üœŒ]+[^t]eur","euse","rice"], 
["[a-zÀ-ÖÙ-öù-üœŒ]+teur","rice","euse","trice","teuse","ice","se"], 
["clown","e","esse"],
["esquimaux","des?","des"],
["br[èe]f","ève"],
["exprès","exprès"],
["fra[iî]s?","che","aîche"],
["prophète","sse","esse"],
["foufou","olle"],
["héros","oïne"],
["bigouden","ène"],
["o?uzbek","èke"],
["(ép|jal)oux","ouse","se"],
["roux","ousse","sse"],
["faux","ausse","sse"],
["bel|nouvel|vieil|fol|mol","le"],
["doux","ouce","ce"],
["([mf])ou","olle"],
["tiers","ce"],
["s[èe]c","he","èche"],
["copain","ine"],
["compagnon","agne"],
["(bén|mal)in","igne"],
["chef","fe","fesse"],
["(las|bas|gros|gras|épais)","se"],
["[a-zÀ-ÖÙ-öù-üœŒ]+teur","rice","euse"]
];